### ISSUE TITLE
Embedd Youtube Video

### ISSUE THREAD

**Issue by erandevishal** [bahriddin/ckeditor-html5-video#17]
I want to embedd youtube video on my website using the youtube video link. 
Is it possible using this plugin? If not, is the plugin supposed to be updated in near future to add that feature? Again if not, what changes need I to do in the code??

**Comment by Cyrille37** [comment]
Hi
There are several plugins that already do that:

[Auto Embed](https://ckeditor.com/cke4/addon/autoembed), [Media Embed](https://ckeditor.com/cke4/addon/embed) and [Semantic Media Embed](https://ckeditor.com/cke4/addon/embedsemantic) for inserting embedded media resources like videos (e.g. from YouTube, Vimeo), tweets or slideshows.
