### ISSUE TITLE
Invalid extension

### ISSUE THREAD

**Issue by Pogoss** [bahriddin/ckeditor-html5-video#5]
Hi,

When i try to upload .mp4 file to ckeditor i'm getting this error
"small.mp4 has invalid extension. Only doc, docx, xls, out, dos, pdf, rar, zip, tar, tar.gz, swf are allowed."

Can't figure out how to fix this. Thanks

**Comment by valadas** [comment]
This issue is not related to this plugin, allowed file extensions are set in your file browser.

**Comment by bahriddin** [comment]
Great!
