### ISSUE TITLE
Permissions on uploaded videos

### ISSUE THREAD

**Issue by newstaircase** [bahriddin/ckeditor-html5-video#6]
I have successfully added the HTML5 Video plugin to CKEditor in my Django project, and am able to use it to upload videos (thank you!), however the video files are being uploaded with permissions set to 600, meaning that they cannot be played (403 error). If I manually change the permissions of the uploaded file to 755 it all works well, but I need this to be done automatically for files uploaded by my users. Any advice would be much appreciated.

**Comment by cn-jiangfei** [comment]
You need to set the directory to 755
File set to 644
And inherit

**Comment by bahriddin** [comment]
@newstaircase Did you find an answer to your question?
