### ISSUE TITLE
CKEditor HTML5 Audio For Chinese language

### ISSUE THREAD

**Issue by cn-jiangfei** [bahriddin/ckeditor-html5-video#8]
CKEDITOR.plugins.setLang( 'html5video', 'cn', {
    button: '发布HTML5视频',
    title: 'HTML5视频',
    infoLabel: '视频信息',
    allowed: '支持格式: MP4, WebM, Ogv',
    urlMissing: '视频url',
    videoProperties: '视频属性',
    upload: '上传视频',
    btnUpload: '上传',
    advanced: '高级',
    autoplay: '自动播放',
    yes: '是',
    no: '否',
	responsive: '自动宽度'
} );

**Comment by bahriddin** [comment]
Hi, @cn-jiangfei 
Due to my busy student life, I can't help to you until June. After that, I hope I check all issues and do my best!
Cheers!

**Comment by cn-jiangfei** [comment]
Thank you very much. I hope you can increase the poster properties

**Comment by NabiKAZ** [comment]
I created a request pull for this.
pull #10

**Comment by bahriddin** [comment]
Thank you @NabiKAZ for contribution. I think I can close this issue now.
